#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server

if ["$#" -lt 3 ]
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1

elif ["$#" -lt 4]
	scp "$1" "$2@$3": ~/
else
	scp -i "$4" "$1" "$3@$2":~/
fi
