#!/usr/bin/env bash
# Step 1: Install Nginx (if not already installed)

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name_;\n\trewrite ^\/redirect_me/ https:\/\/github.com\/ permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
