#!/usr/bin/env bash
# Install haproxy and confifure your load-balancer using haproxy

sudo apt-get -y update && sudo apt-get -y install haproxy

load_balance="""
frontend http80
    bind *:80
    timeout client 30s
    mode http
    default_backend allserver

backend allserver
    timeout server 5s
    mode http
    server 326556-web-01 54.175.131.198
    server 326556-web-02 34.229.137.18
"""
sudo su root -
echo "$load_balance" >> /etc/haproxy/hapro
sudo service haproxy restart
