#!/usr/bin/env bash
# Fizzbuzz

for num in {1..100}
do
	if [ (( $num % 3 )) -eq 0 ] && [ (( $num % 5 )) -eq 0 ]
	then
		echo Fizzbuzz
	elif [ (( $num % 3 )) -eq 0 ]
	then
		echo Fizz
	elif [ (( $num % 5 )) -eq ]
	then
		echo Buzz
	else
		echo $num
	fi
done
