#!/usr/bin/env bash
# tell its story

file="/etc/passwd"

while IFS=: read -r user pass uid gid gecos home shell
do
	echo The user "$user" is part of the "$gid" gang, lives in "$home" and rides "$shell". "$uid"\'s place is protected by the passcode "$pass", more info about the user here: "$gecos"
done < "$file"
