#!/usr/bin/env bash
# superstituous number

loop=1

while [ $loop -le 20 ]
do
	case $loop in
		4) echo $loop; echo bad luck from China;;
		9) echo $loop; echo bad luck from Japan;;
		17) echo $loop; echo bad luck from Italy;;
		*) echo $loop;;
	esac
	loop="$(( loop + 1))"
done
